# Linter Options
files:
  include: 'sass/**/*.s+(a|c)ss'
  ignore:
    - 'sass/vendor/**/*.*'
    - 'scss/**/_icomoon.scss'
    - 'scss/**/_mixins.scss'
rules:
  extends-before-mixins: 2
  extends-before-declarations: 2
  mixins-before-declarations:
    - 0
    -
      exclude:
        - breakpoint
        - mq
  nesting-depth: 
    - 2
    -
      max-depth: 8
  class-name-format:
   - 0
  no-mergeable-selectors: 0
  no-transition-all: 0
  no-warn: 1
  no-debug: 1
  no-color-literals: 0
  no-ids: 0
  no-important: 0
  no-invalid-hex: 0
  leading-zero: 0
  placeholder-in-extend: 0 
  no-css-comments: 0
  no-duplicate-properties:
    - 1
    -
      exclude:
        - src
  hex-notation:
    - 2
    -
      style: lowercase
  indentation:
    - 2
    -
      size: 2
  property-sort-order:
    - 1
    -
      order:
        - display
        - margin
      ignore-custom-properties: true
  variable-for-property:
    - 2
    -
      properties:
        - color
        - background-color
